# Regresion Linear 

In [7]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np 


In [9]:
data= pd.read_csv("../python-ml-course/datasets/ads/Advertising.csv")

In [11]:
feature_cols = ["TV","Radio","Newspaper"]

In [16]:
x = data[feature_cols]
y = data["Sales"]

In [17]:
estimator = SVR(kernel="linear")
selector = RFE(estimator,2 ,step=1)
selector = selector.fit(x,y)

In [20]:
selector.support_

array([ True,  True, False])

In [22]:
selector.ranking_

array([1, 1, 2])

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
x_pred =x[["TV","Radio"]]

In [26]:
lm = LinearRegression()
lm.fit(x_pred, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [27]:
lm.intercept_



2.9210999124051362

In [28]:
lm.coef_

array([0.04575482, 0.18799423])

In [29]:
lm.score(x_pred, y)

0.8971942610828956