# Metodo K-means

In [1]:
import pandas as pd
import numpy as np


In [6]:
data = np.random.random(90).reshape(30,3)

In [7]:
data

array([[0.77204015, 0.71516986, 0.74818819],
       [0.69158648, 0.92620023, 0.5921254 ],
       [0.6139207 , 0.12373595, 0.70610309],
       [0.40828132, 0.11909359, 0.29580933],
       [0.67076581, 0.04507363, 0.10820228],
       [0.40192044, 0.48950808, 0.08373332],
       [0.5968308 , 0.4589713 , 0.00336564],
       [0.07865267, 0.20303417, 0.71867824],
       [0.80393493, 0.77270446, 0.12674588],
       [0.6064449 , 0.08820127, 0.47781525],
       [0.3026056 , 0.33681683, 0.14037296],
       [0.11321879, 0.68348109, 0.70679022],
       [0.03160367, 0.15987328, 0.50275774],
       [0.55717743, 0.01347939, 0.25269863],
       [0.012513  , 0.5300534 , 0.62665662],
       [0.11089645, 0.26472003, 0.2588675 ],
       [0.59691489, 0.01069692, 0.84309852],
       [0.36993484, 0.19302323, 0.51300946],
       [0.69549476, 0.73491385, 0.85368107],
       [0.740521  , 0.13993042, 0.86125496],
       [0.63014969, 0.02974784, 0.48887942],
       [0.96725991, 0.71472015, 0.51839636],
       [0.

In [12]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_center = np.vstack([data[c1], data[c2]])

In [13]:
clust_center

array([[0.012513  , 0.5300534 , 0.62665662],
       [0.96725991, 0.71472015, 0.51839636]])

In [14]:
c1
c2

21

In [15]:
c1

14

In [16]:
from scipy.cluster.vq import vq

In [17]:
vq(data, clust_center)

(array([1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
        0, 1, 1, 1, 0, 0, 0, 0]),
 array([0.30152154, 0.35518394, 0.71368392, 0.65953048, 0.83940122,
        0.66936371, 0.6840189 , 0.34609827, 0.42828416, 0.72412721,
        0.5983025 , 0.2002576 , 0.39083079, 0.83866121, 0.        ,
        0.46405812, 0.81123598, 0.50423742, 0.43206472, 0.70664404,
        0.76400368, 0.        , 0.50223084, 0.57663698, 0.30421501,
        0.35290159, 0.48216113, 0.15181689, 0.55162301, 0.42523322]))

In [18]:
from scipy.cluster.vq import kmeans

In [21]:
kmeans(data, clust_center)

(array([[0.40743915, 0.26168023, 0.4760713 ],
        [0.6986144 , 0.76370518, 0.59454406]]), 0.3536669601897121)

In [23]:
kmeans(data , 20)

(array([[0.11089645, 0.26472003, 0.2588675 ],
        [0.03160367, 0.15987328, 0.50275774],
        [0.32489155, 0.36374545, 0.86242048],
        [0.80200415, 0.24161862, 0.23313212],
        [0.41603844, 0.22986978, 0.4790122 ],
        [0.07865267, 0.20303417, 0.71867824],
        [0.012513  , 0.5300534 , 0.62665662],
        [0.80393493, 0.77270446, 0.12674588],
        [0.3026056 , 0.33681683, 0.14037296],
        [0.7675016 , 0.73781128, 0.79662007],
        [0.65690852, 0.84497869, 0.58305319],
        [0.96725991, 0.71472015, 0.51839636],
        [0.46405822, 0.61336758, 0.42318309],
        [0.5968308 , 0.4589713 , 0.00336564],
        [0.43595473, 0.86916317, 0.72660467],
        [0.40192044, 0.48950808, 0.08373332],
        [0.6504522 , 0.09145443, 0.80348552],
        [0.61829729, 0.05897456, 0.48334733],
        [0.61397162, 0.02927651, 0.18045046],
        [0.11514701, 0.65323443, 0.69621202]]), 0.051353676184907576)